id: P000422
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W4CZ74360
  title: འཁོར་ལོ་སྡོམ་པའི་མངོན་རྟོགས་ནག་འགྲོས་སུ་བཀོད་པ་སོགས།
  author: ''
  volumes:
    7627736476994e8dbdc91476711c3590:
      image_group_id: I4CZ74362
      title: Volume 1 of 'khor lo sdom pa'i mngon rtogs nag 'gros su bkod pa/
      volume_number: 1
      total_pages: 166
      base_file: v001.txt
