id: opecha:P000422
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74360
  title: འཁོར་ལོ་སྡོམ་པའི་མངོན་རྟོགས་ནག་འགྲོས་སུ་བཀོད་པ་སོགས།
  volume:
    7627736476994e8dbdc91476711c3590:
      image_group_id: I4CZ74362
      title: Volume 1 of 'khor lo sdom pa'i mngon rtogs nag 'gros su bkod pa/
      volume_number: 1
      total_pages: 166
  author: ''
ebook_metadata:
  title: འཁོར་ལོ་སྡོམ་པའི་མངོན་རྟོགས་ནག་འགྲོས་སུ་བཀོད་པ་སོགས།
  author: ''
  sku: P000422
  cover: cover.jpg
  layers:
  - pagination
